/*
 *
 * Copyright 2019 Dtji Psimfans (Admin and creator of "Global App Developers @ Jogja" Facebook group)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
*/

var buildings = [ // name, description, amount, coinCost, IDRCost, mCubeCost, kWhCost, workerCost, visitorCost, emptySpaceCost, specialCoinCost, coinProductionRate, IDRProductionRate, mCubeProductionRate, kWhProductionRate, workerProductionRate, visitorProductionRate, emptySpaceProductionRate, specialCoinProductionRate, actualCoinProductionRate, actualIDRProductionRate, actualmCubeProductionRate, actualkWhProductionRate, actualWorkerProductionRate, actualVisitorProductionRate, actualEmptySpaceProductionRate, actualSpecialCoinProductionRate, requirements, unlocked
    new Building("Reservoir", "Building to increase yield of water and electricity.", new Decimal(0), new Decimal(10000000), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(10000), new Decimal(10000), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), null, true),
    new Building("Money Making Machine", "Building to make Indonesian Rupiahs from coins.", new Decimal(0), new Decimal(10000000), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(10000), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), null, true),
    new Building("Wonolelo Jogja Hills (Level 1)", "A housing estate in Wonolelo village, Pleret, Bantul Regency (Level 1).", new Decimal(0), new Decimal(50000), new Decimal(5000), new Decimal(100), new Decimal(10), new Decimal(1), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(5000), new Decimal(0), new Decimal(-10), new Decimal(-1), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), null, true),
    new Building("Griya Ploso Asri (Level 1)", "A housing estate developed by Parahyangan Abadi Land in Sentolo, Kulon Progo Regency (Level 1).", new Decimal(0), new Decimal(5e9), new Decimal(5e7), new Decimal(1000), new Decimal(100), new Decimal(10), new Decimal(1), new Decimal(0), new Decimal(0), new Decimal(5e6), new Decimal(0), new Decimal(-100), new Decimal(-10), new Decimal(1), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e9)), false),
    new Building("Pal Gading Regency (Level 1)", "A housing estate developed by Property Syariah near Wonosari (capital of Gunungkidul Regency) (Level 1).", new Decimal(0), new Decimal(5e14), new Decimal(5e11), new Decimal(10000), new Decimal(1000), new Decimal(100), new Decimal(10), new Decimal(1), new Decimal(0), new Decimal(5e9), new Decimal(0), new Decimal(-1000), new Decimal(-100), new Decimal(10), new Decimal(1), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e14)), false),
    new Building("Griya Bangun Permai (Level 1)", "A housing estate with unknown developer. This housing estate is located in Bangunjiwo village, Kasihan, Bantul Regency (Level 1).", new Decimal(0), new Decimal(5e19), new Decimal(5e15), new Decimal(100000), new Decimal(10000), new Decimal(1000), new Decimal(100), new Decimal(10), new Decimal(0), new Decimal(5e12), new Decimal(0), new Decimal(-10000), new Decimal(-1000), new Decimal(100), new Decimal(10), new Decimal(1), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e19)), false),
    new Building("Griya Argatama Step 2 (Level 1)", "A housing estate developed by Devcorena Cipta Grahatama in Trimulyo village, Jetis, Bantul Regency (Level 1).", new Decimal(0), new Decimal(5e24), new Decimal(5e19), new Decimal(1000000), new Decimal(100000), new Decimal(10000), new Decimal(1000), new Decimal(100), new Decimal(0), new Decimal(5e15), new Decimal(0), new Decimal(-100000), new Decimal(-10000), new Decimal(1000), new Decimal(100), new Decimal(10), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e24)), false),
    new Building("Puri Surya Bangunjiwo 1 (Level 1)", "A housing estate developed by Surya Jaya Persada in Bangunjiwo village, Kasihan, Bantul Regency (Level 1).", new Decimal(0), new Decimal(5e29), new Decimal(5e23), new Decimal(10000000), new Decimal(1000000), new Decimal(100000), new Decimal(10000), new Decimal(1000), new Decimal(0), new Decimal(5e18), new Decimal(0), new Decimal(-1000000), new Decimal(-100000), new Decimal(10000), new Decimal(1000), new Decimal(100), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e29)), false),
    new Building("Citra Wonosari (Level 1)", "A housing estate in Karangrejek village, Wonosari (capital of Gunungkidul Regency) which has a strategic location (i.e. near Baron Street) (Level 1).", new Decimal(0), new Decimal(5e34), new Decimal(5e27), new Decimal(100000000), new Decimal(10000000), new Decimal(1000000), new Decimal(100000), new Decimal(10000), new Decimal(0), new Decimal(5e21), new Decimal(0), new Decimal(-10000000), new Decimal(-1000000), new Decimal(100000), new Decimal(10000), new Decimal(1000), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e34)), false),
    new Building("The Mountain (Level 1)", "A housing estate developed by Meckatara Bersama Abadi in Giripeni village, Wates (capital of Kulon Progo), Kulon Progo Regency (Level 1).", new Decimal(0), new Decimal(5e39), new Decimal(5e31), new Decimal(1e9), new Decimal(100000000), new Decimal(10000000), new Decimal(1000000), new Decimal(100000), new Decimal(0), new Decimal(5e24), new Decimal(0), new Decimal(-100000000), new Decimal(-10000000), new Decimal(1000000), new Decimal(100000), new Decimal(10000), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e39)), false),
    new Building("Green Harmony Sedayu (Level 1)", "A housing estate developed by Puriland Development located in front of Pajangan State Middle School in Sedayu, Bantul Regency (Level 1).", new Decimal(0), new Decimal(5e44), new Decimal(5e35), new Decimal(1e10), new Decimal(1e9), new Decimal(100000000), new Decimal(10000000), new Decimal(1000000), new Decimal(0), new Decimal(5e27), new Decimal(0), new Decimal(-1e9), new Decimal(-100000000), new Decimal(10000000), new Decimal(1000000), new Decimal(100000), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e44)), false),
    new Building("Taman Darusalam Jogja (Level 1)", "A housing estate near Wates street (in Argomulyo village, Sedayu, Bantul Regency) (Level 1).", new Decimal(0), new Decimal(5e49), new Decimal(5e39), new Decimal(1e11), new Decimal(1e10), new Decimal(1e9), new Decimal(100000000), new Decimal(10000000), new Decimal(0), new Decimal(5e30), new Decimal(0), new Decimal(-1e10), new Decimal(-1e9), new Decimal(100000000), new Decimal(10000000), new Decimal(1000000), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e49)), false),
    new Building("Griya Mustika Sedayu (Level 1)", "A housing estate developed by Mustika Asri Group in the 12th kilometer of Wates Street, Sedayu, Bantul Regency (Level 1).", new Decimal(0), new Decimal(5e54), new Decimal(5e43), new Decimal(1e12), new Decimal(1e11), new Decimal(1e10), new Decimal(1e9), new Decimal(100000000), new Decimal(0), new Decimal(5e33), new Decimal(0), new Decimal(-1e11), new Decimal(-1e10), new Decimal(1e9), new Decimal(100000000), new Decimal(10000000), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e54)), false),
    new Building("Quariza Bangunjiwo 2 (Level 1)", "A housing estate developed by Quares Group in Bangunjiwo village, Kasihan, Bantul Regency (Level 1).", new Decimal(0), new Decimal(5e59), new Decimal(5e47), new Decimal(1e13), new Decimal(1e12), new Decimal(1e11), new Decimal(1e10), new Decimal(1e9), new Decimal(0), new Decimal(5e36), new Decimal(0), new Decimal(-1e12), new Decimal(-1e11), new Decimal(1e10), new Decimal(1e9), new Decimal(100000000), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e59)), false),
    new Building("Bumi Sedayu (Level 1)", "A housing estate developed by Hilmy Jaya Sejahtera in the 10th kilometer of Wates Street, Argomulyo village, Sedayu, Bantul Regency (Level 1).", new Decimal(0), new Decimal(5e64), new Decimal(5e51), new Decimal(1e14), new Decimal(1e13), new Decimal(1e12), new Decimal(1e11), new Decimal(1e10), new Decimal(0), new Decimal(5e39), new Decimal(0), new Decimal(-1e13), new Decimal(-1e12), new Decimal(1e11), new Decimal(1e10), new Decimal(1e9), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e64)), false),
    new Building("Green Mutiara Java Regency (Level 1)", "A housing estate developed by KSO PPAK RC in Pajangan, Bantul Regency (Level 1).", new Decimal(0), new Decimal(5e69), new Decimal(5e55), new Decimal(1e15), new Decimal(1e14), new Decimal(1e13), new Decimal(1e12), new Decimal(1e11), new Decimal(0), new Decimal(5e42), new Decimal(0), new Decimal(-1e14), new Decimal(-1e13), new Decimal(1e12), new Decimal(1e11), new Decimal(1e10), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e69)), false),
    new Building("Green Tasneem Bangunjiwo (Level 1)", "A housing estate developed by Falah Radians in Bangunjiwo village, Kasihan, Bantul Regency (Level 1).", new Decimal(0), new Decimal(5e74), new Decimal(5e59), new Decimal(1e16), new Decimal(1e15), new Decimal(1e14), new Decimal(1e13), new Decimal(1e12), new Decimal(0), new Decimal(5e45), new Decimal(0), new Decimal(-1e15), new Decimal(-1e14), new Decimal(1e13), new Decimal(1e12), new Decimal(1e11), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e74)), false),
    new Building("Fortuna Mansion Wonokromo (Level 1)", "A housing estate with unknown developer in Wonokromo village, Pleret, Bantul Regency (Level 1).", new Decimal(0), new Decimal(5e79), new Decimal(5e63), new Decimal(1e17), new Decimal(1e16), new Decimal(1e15), new Decimal(1e14), new Decimal(1e13), new Decimal(0), new Decimal(5e48), new Decimal(0), new Decimal(-1e16), new Decimal(-1e15), new Decimal(1e14), new Decimal(1e13), new Decimal(1e12), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e79)), false),
    new Building("Fortuna Mansion (Level 1)", "A housing estate in Tamanan village, Banguntapan, Bantul Regency (Level 1).", new Decimal(0), new Decimal(5e84), new Decimal(5e67), new Decimal(1e18), new Decimal(1e17), new Decimal(1e16), new Decimal(1e15), new Decimal(1e14), new Decimal(0), new Decimal(5e51), new Decimal(0), new Decimal(-1e17), new Decimal(-1e16), new Decimal(1e15), new Decimal(1e14), new Decimal(1e13), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e84)), false),
    new Building("Imperia Plazza (Level 1)", "A housing estate developed by Fortuna Land in Margoluwih village, Seyegan, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e89), new Decimal(5e71), new Decimal(1e19), new Decimal(1e18), new Decimal(1e17), new Decimal(1e16), new Decimal(1e15), new Decimal(0), new Decimal(5e54), new Decimal(0), new Decimal(-1e18), new Decimal(-1e17), new Decimal(1e16), new Decimal(1e15), new Decimal(1e14), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e89)), false),
    new Building("Rock Regency (Level 1)", "A housing estate developed by Bahtera Penta Wijaya in Wates (capital of Kulon Progo Regency), Kulon Progo (Level 1).", new Decimal(0), new Decimal(5e94), new Decimal(5e75), new Decimal(1e20), new Decimal(1e19), new Decimal(1e18), new Decimal(1e17), new Decimal(1e16), new Decimal(0), new Decimal(5e57), new Decimal(0), new Decimal(-1e19), new Decimal(-1e18), new Decimal(1e17), new Decimal(1e16), new Decimal(1e15), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e94)), false),
    new Building("Fasco Village Bangunjiwo (Level 1)", "A housing estate developed by Asa Persada in Bangunjiwo village, Kasihan, Bantul Regency (Level 1).", new Decimal(0), new Decimal(5e99), new Decimal(5e79), new Decimal(1e21), new Decimal(1e20), new Decimal(1e19), new Decimal(1e18), new Decimal(1e17), new Decimal(0), new Decimal(5e60), new Decimal(0), new Decimal(-1e20), new Decimal(-1e19), new Decimal(1e18), new Decimal(1e17), new Decimal(1e16), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e99)), false),
    new Building("Green Jasmine Residence (Level 1)", "A housing estate near the office of the headman of Bangunjiwo village, Kasihan, Bantul Regency (Level 1).", new Decimal(0), new Decimal(5e104), new Decimal(5e83), new Decimal(1e22), new Decimal(1e21), new Decimal(1e20), new Decimal(1e19), new Decimal(1e18), new Decimal(0), new Decimal(5e63), new Decimal(0), new Decimal(-1e21), new Decimal(-1e20), new Decimal(1e19), new Decimal(1e18), new Decimal(1e17), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e104)), false),
    new Building("The Violet Light (Level 1)", "A housing estate developed by Meckatara Bersama Abadi in Karang Asem village, Pengasih, Kulon Progo Regency (Level 1).", new Decimal(0), new Decimal(5e109), new Decimal(5e87), new Decimal(1e23), new Decimal(1e22), new Decimal(1e21), new Decimal(1e20), new Decimal(1e19), new Decimal(0), new Decimal(5e66), new Decimal(0), new Decimal(-1e22), new Decimal(-1e21), new Decimal(1e20), new Decimal(1e19), new Decimal(1e18), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e109)), false),
    new Building("Jingga Residence (Level 1)", "A housing estate developed by Nirmana Utama in the 8th kilometer of Wates Street, Balecatur village, Gamping, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e114), new Decimal(5e91), new Decimal(1e24), new Decimal(1e23), new Decimal(1e22), new Decimal(1e21), new Decimal(1e20), new Decimal(0), new Decimal(5e69), new Decimal(0), new Decimal(-1e23), new Decimal(-1e22), new Decimal(1e21), new Decimal(1e20), new Decimal(1e19), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e114)), false),
    new Building("Naraya Residence (Level 1)", "A housing estate with unknown developer in Tamantirto village, Kasihan, Bantul Regency (Level 1).", new Decimal(0), new Decimal(5e119), new Decimal(5e95), new Decimal(1e25), new Decimal(1e24), new Decimal(1e23), new Decimal(1e22), new Decimal(1e21), new Decimal(0), new Decimal(5e72), new Decimal(0), new Decimal(-1e24), new Decimal(-1e23), new Decimal(1e22), new Decimal(1e21), new Decimal(1e20), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e119)), false),
    new Building("Griya Safir Citra Pesona (Level 1)", "A housing estate developed by Griya Mataram Singgasana in Triharjo village, Sleman, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e124), new Decimal(5e99), new Decimal(1e26), new Decimal(1e25), new Decimal(1e24), new Decimal(1e23), new Decimal(1e22), new Decimal(0), new Decimal(5e75), new Decimal(0), new Decimal(-1e25), new Decimal(-1e24), new Decimal(1e23), new Decimal(1e22), new Decimal(1e21), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e124)), false),
    new Building("Ndalem Agung Bangunjiwo (Level 1)", "A housing estate with a strategic location. It is near Kasongan tourist destination and the city centre of Jogja. It's location is in Bangunjiwo village, Kasihan, Bantul Regency (Level 1).", new Decimal(0), new Decimal(5e129), new Decimal(5e103), new Decimal(1e27), new Decimal(1e26), new Decimal(1e25), new Decimal(1e24), new Decimal(1e23), new Decimal(0), new Decimal(5e78), new Decimal(0), new Decimal(-1e26), new Decimal(-1e25), new Decimal(1e24), new Decimal(1e23), new Decimal(1e22), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e129)), false),
    new Building("Amarta Purwomartani (Level 1)", "A housing estate with unknown developer in Purwomartani village, Kalasan, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e134), new Decimal(5e107), new Decimal(1e28), new Decimal(1e27), new Decimal(1e26), new Decimal(1e25), new Decimal(1e24), new Decimal(0), new Decimal(5e81), new Decimal(0), new Decimal(-1e27), new Decimal(-1e26), new Decimal(1e25), new Decimal(1e24), new Decimal(1e23), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e134)), false),
    new Building("Bukit Mutiara Residence (Level 1)", "A housing estate in Ambarketawang village, Gamping, Sleman Regency which is near a market, hospital, and two campuses (Level 1).", new Decimal(0), new Decimal(5e139), new Decimal(5e111), new Decimal(1e29), new Decimal(1e28), new Decimal(1e27), new Decimal(1e26), new Decimal(1e25), new Decimal(0), new Decimal(5e84), new Decimal(0), new Decimal(-1e28), new Decimal(-1e27), new Decimal(1e26), new Decimal(1e25), new Decimal(1e24), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e139)), false),
    new Building("Metro Harmony Ciptahasta (Level 1)", "A housing estate developed by Metro Harmony Ciptahasta in Tirtoadi village, Mlati, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e144), new Decimal(5e115), new Decimal(1e30), new Decimal(1e29), new Decimal(1e28), new Decimal(1e27), new Decimal(1e26), new Decimal(0), new Decimal(5e87), new Decimal(0), new Decimal(-1e29), new Decimal(-1e28), new Decimal(1e27), new Decimal(1e26), new Decimal(1e25), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e144)), false),
    new Building("Adara Citra (Level 1)", "A housing estate developed by Citra Kedaton in the 10th kilometer of Jogja-Solo Street (north of UKRIM campus), Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e149), new Decimal(5e119), new Decimal(1e31), new Decimal(1e30), new Decimal(1e29), new Decimal(1e28), new Decimal(1e27), new Decimal(0), new Decimal(5e90), new Decimal(0), new Decimal(-1e30), new Decimal(-1e29), new Decimal(1e28), new Decimal(1e27), new Decimal(1e26), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e149)), false),
    new Building("Pondok Permai Giwangan (Level 1)", "A housing estate near Giwangan Bus Terminal (a famous bus terminal in the city of Jogja) (Level 1).", new Decimal(0), new Decimal(5e154), new Decimal(5e123), new Decimal(1e32), new Decimal(1e31), new Decimal(1e30), new Decimal(1e29), new Decimal(1e28), new Decimal(0), new Decimal(5e93), new Decimal(0), new Decimal(-1e31), new Decimal(-1e30), new Decimal(1e29), new Decimal(1e28), new Decimal(1e27), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e154)), false),
    new Building("Amartani Palagan Residence (Level 1)", "A housing estate developed by Trah Development in the 9th kilometer of Palagan Street, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e159), new Decimal(5e127), new Decimal(1e33), new Decimal(1e32), new Decimal(1e31), new Decimal(1e30), new Decimal(1e29), new Decimal(0), new Decimal(5e96), new Decimal(0), new Decimal(-1e32), new Decimal(-1e31), new Decimal(1e30), new Decimal(1e29), new Decimal(1e28), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e159)), false),
    new Building("Griya Nuansa Citra (Level 1)", "A housing estate in a strategic location (i.e. near Wates Street and the west part of Jogja's ring road (Level 1).", new Decimal(0), new Decimal(5e164), new Decimal(5e131), new Decimal(1e34), new Decimal(1e33), new Decimal(1e32), new Decimal(1e31), new Decimal(1e30), new Decimal(0), new Decimal(5e99), new Decimal(0), new Decimal(-1e33), new Decimal(-1e32), new Decimal(1e31), new Decimal(1e30), new Decimal(1e29), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e164)), false),
    new Building("Pondok Permai Tamantirto 1 Step 3 (Level 1)", "A housing estate developed by Sumber Baru Land in the west part of Jogja's ring road (east of UMY campus), Tamantirto village, Kasihan, Bantul Regency (Level 1).", new Decimal(0), new Decimal(5e169), new Decimal(5e135), new Decimal(1e35), new Decimal(1e34), new Decimal(1e33), new Decimal(1e32), new Decimal(1e31), new Decimal(0), new Decimal(5e102), new Decimal(0), new Decimal(-1e34), new Decimal(-1e33), new Decimal(1e32), new Decimal(1e31), new Decimal(1e30), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e169)), false),
    new Building("Royal Mansion Banguntapan (Level 1)", "A housing estate near Balong Waterpark. It is located in Jambidan village, Banguntapan, Bantul Regency (Level 1).", new Decimal(0), new Decimal(5e174), new Decimal(5e139), new Decimal(1e36), new Decimal(1e35), new Decimal(1e34), new Decimal(1e33), new Decimal(1e32), new Decimal(0), new Decimal(5e105), new Decimal(0), new Decimal(-1e35), new Decimal(-1e34), new Decimal(1e33), new Decimal(1e32), new Decimal(1e31), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e174)), false),
    new Building("Balegong Residence (Level 1)", "A housing estate developed by Tiga Beringin Sejahtera in Kebon Agung Street, Cebongan, Mlati, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e179), new Decimal(5e143), new Decimal(1e37), new Decimal(1e36), new Decimal(1e35), new Decimal(1e34), new Decimal(1e33), new Decimal(0), new Decimal(5e108), new Decimal(0), new Decimal(-1e36), new Decimal(-1e35), new Decimal(1e34), new Decimal(1e33), new Decimal(1e32), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e179)), false),
    new Building("Puri Niten Asri (Level 1)", "A housing estate near the rice fields, Tajem Street, and Budi Mulia Dua International Middle and High School in Wedomartani village, Ngemplak, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e184), new Decimal(5e147), new Decimal(1e38), new Decimal(1e37), new Decimal(1e36), new Decimal(1e35), new Decimal(1e34), new Decimal(0), new Decimal(5e111), new Decimal(0), new Decimal(-1e37), new Decimal(-1e36), new Decimal(1e35), new Decimal(1e34), new Decimal(1e33), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e184)), false),
    new Building("Citra Grand Mutiara Yogyakarta (Level 1)", "A waterpark residence in the 9th kilometer of Wates Street, Gamping, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e189), new Decimal(5e151), new Decimal(1e39), new Decimal(1e38), new Decimal(1e37), new Decimal(1e36), new Decimal(1e35), new Decimal(0), new Decimal(5e114), new Decimal(0), new Decimal(-1e38), new Decimal(-1e37), new Decimal(1e36), new Decimal(1e35), new Decimal(1e34), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e189)), false),
    new Building("The Residence Blok - I (Level 1)", "A housing estate developed by Bhumi Setra Rizqi in the 5.5th kilometer of Wates Street, Ambarketawang village, Gamping, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e194), new Decimal(5e155), new Decimal(1e40), new Decimal(1e39), new Decimal(1e38), new Decimal(1e37), new Decimal(1e36), new Decimal(0), new Decimal(5e117), new Decimal(0), new Decimal(-1e39), new Decimal(-1e38), new Decimal(1e37), new Decimal(1e36), new Decimal(1e35), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e194)), false),
    new Building("Griya Alvita (Level 1)", "A housing estate developed by Griya Mataram Singgasana in the 3rd kilometer of Wates Street, Ngestiharjo village, Kasihan, Bantul Regency (Level 1).", new Decimal(0), new Decimal(5e199), new Decimal(5e159), new Decimal(1e41), new Decimal(1e40), new Decimal(1e39), new Decimal(1e38), new Decimal(1e37), new Decimal(0), new Decimal(5e120), new Decimal(0), new Decimal(-1e40), new Decimal(-1e39), new Decimal(1e38), new Decimal(1e37), new Decimal(1e36), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e199)), false),
    new Building("Tajem Griya Amana (Level 1)", "A housing estate developed by Dwitata Pratama near Tajem Street in Maguwoharjo village, Depok, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e204), new Decimal(5e163), new Decimal(1e42), new Decimal(1e41), new Decimal(1e40), new Decimal(1e39), new Decimal(1e38), new Decimal(0), new Decimal(5e123), new Decimal(0), new Decimal(-1e41), new Decimal(-1e40), new Decimal(1e39), new Decimal(1e38), new Decimal(1e37), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e204)), false),
    new Building("Green Land Permata (Level 1)", "A housing estate near Tajem Street and Jogja's North Ring Road in Maguwoharjo village, Depok, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e209), new Decimal(5e167), new Decimal(1e43), new Decimal(1e42), new Decimal(1e41), new Decimal(1e40), new Decimal(1e39), new Decimal(0), new Decimal(5e126), new Decimal(0), new Decimal(-1e42), new Decimal(-1e41), new Decimal(1e40), new Decimal(1e39), new Decimal(1e38), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e209)), false),
    new Building("Pondok Permai Mlati 2 (Level 1)", "A housing estate developed by Sumber Baru Land in Kebon Agung Street, Mlati, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e214), new Decimal(5e171), new Decimal(1e44), new Decimal(1e43), new Decimal(1e42), new Decimal(1e41), new Decimal(1e40), new Decimal(0), new Decimal(5e129), new Decimal(0), new Decimal(-1e43), new Decimal(-1e42), new Decimal(1e41), new Decimal(1e40), new Decimal(1e39), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e214)), false),
    new Building("Royal Maguwo (Level 1)", "A housing estate developed by Saraswanti Hasil Makmur in Purwomartani village, Kalasan, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e219), new Decimal(5e175), new Decimal(1e45), new Decimal(1e44), new Decimal(1e43), new Decimal(1e42), new Decimal(1e41), new Decimal(0), new Decimal(5e132), new Decimal(0), new Decimal(-1e44), new Decimal(-1e43), new Decimal(1e42), new Decimal(1e41), new Decimal(1e40), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e219)), false),
    new Building("The Grand Amartani Maguwo (Level 1)", "A housing estate near Maguwoharjo Stadium, Depok, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e224), new Decimal(5e179), new Decimal(1e46), new Decimal(1e45), new Decimal(1e44), new Decimal(1e43), new Decimal(1e42), new Decimal(0), new Decimal(5e135), new Decimal(0), new Decimal(-1e45), new Decimal(-1e44), new Decimal(1e43), new Decimal(1e42), new Decimal(1e41), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e224)), false),
    new Building("Banteng Townhouse (Level 1)", "A housing estate developed by Agatama Putra in Banteng, Sinduharjo village, Ngaglik, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e229), new Decimal(5e183), new Decimal(1e47), new Decimal(1e46), new Decimal(1e45), new Decimal(1e44), new Decimal(1e43), new Decimal(0), new Decimal(5e138), new Decimal(0), new Decimal(-1e46), new Decimal(-1e45), new Decimal(1e44), new Decimal(1e43), new Decimal(1e42), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e229)), false),
    new Building("The Paradise (Level 1)", "A housing estate developed by Sarana Anugrah Pratama LLC near Palagan Street, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e234), new Decimal(5e187), new Decimal(1e48), new Decimal(1e47), new Decimal(1e46), new Decimal(1e45), new Decimal(1e44), new Decimal(0), new Decimal(5e141), new Decimal(0), new Decimal(-1e47), new Decimal(-1e46), new Decimal(1e45), new Decimal(1e44), new Decimal(1e43), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e234)), false),
    new Building("Maguwo Regency (Level 1)", "A housing estate developed by Putera Sakti in Maguwoharjo village, Depok, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e239), new Decimal(5e191), new Decimal(1e49), new Decimal(1e48), new Decimal(1e47), new Decimal(1e46), new Decimal(1e45), new Decimal(0), new Decimal(5e144), new Decimal(0), new Decimal(-1e48), new Decimal(-1e47), new Decimal(1e46), new Decimal(1e45), new Decimal(1e44), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e239)), false),
    new Building("Mustika Asri Residence (Level 1)", "A housing estate developed by Mustika Asri Group in Gebang, Wedomartani village, Ngemplak, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e244), new Decimal(5e195), new Decimal(1e50), new Decimal(1e49), new Decimal(1e48), new Decimal(1e47), new Decimal(1e46), new Decimal(0), new Decimal(5e147), new Decimal(0), new Decimal(-1e49), new Decimal(-1e48), new Decimal(1e47), new Decimal(1e46), new Decimal(1e45), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e244)), false),
    new Building("Pondok Permai Palagan 3 (Level 1)", "A housing estate developed by Sumber Baru Land in the 6th kilometer of Palagan Street (north of Hyatt Regency Hotel), Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e249), new Decimal(5e199), new Decimal(1e51), new Decimal(1e50), new Decimal(1e49), new Decimal(1e48), new Decimal(1e47), new Decimal(0), new Decimal(5e150), new Decimal(0), new Decimal(-1e50), new Decimal(-1e49), new Decimal(1e48), new Decimal(1e47), new Decimal(1e46), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e249)), false),
    new Building("Fasco Mansion Residence (Level 1)", "A housing estate developed by Asa Persada in the 10th kilometer of Palagan Street, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e254), new Decimal(5e203), new Decimal(1e52), new Decimal(1e51), new Decimal(1e50), new Decimal(1e49), new Decimal(1e48), new Decimal(0), new Decimal(5e153), new Decimal(0), new Decimal(-1e51), new Decimal(-1e50), new Decimal(1e49), new Decimal(1e48), new Decimal(1e47), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e254)), false),
    new Building("Villa Estetika (Level 1)", "A housing estate developed by Tunggal Putra Bahagia Sejahtera near Adisucipto Airport, Maguwoharjo village, Depok, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e259), new Decimal(5e207), new Decimal(1e53), new Decimal(1e52), new Decimal(1e51), new Decimal(1e50), new Decimal(1e49), new Decimal(0), new Decimal(5e156), new Decimal(0), new Decimal(-1e52), new Decimal(-1e51), new Decimal(1e50), new Decimal(1e49), new Decimal(1e48), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e259)), false),
    new Building("Taman Palagan Asri 3 Step 2 (Level 1)", "A housing estate developed by Roda Pembangunan Jaya in the 10th kilometer of Palagan Street, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e264), new Decimal(5e211), new Decimal(1e54), new Decimal(1e53), new Decimal(1e52), new Decimal(1e51), new Decimal(1e50), new Decimal(0), new Decimal(5e159), new Decimal(0), new Decimal(-1e53), new Decimal(-1e52), new Decimal(1e51), new Decimal(1e50), new Decimal(1e49), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e264)), false),
    new Building("Jambusari Indah Housing Estate (Level 1)", "A housing estate near Gebang Temple in Condongcatur village, Depok, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e269), new Decimal(5e215), new Decimal(1e55), new Decimal(1e54), new Decimal(1e53), new Decimal(1e52), new Decimal(1e51), new Decimal(0), new Decimal(5e162), new Decimal(0), new Decimal(-1e54), new Decimal(-1e53), new Decimal(1e52), new Decimal(1e51), new Decimal(1e50), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e269)), false),
    new Building("Casa Grande Housing Estate (Level 1)", "An expensive housing estate near Jogja's North Ring Road which has facilities such as swimming pools and a tennis court in Maguwoharjo village, Depok, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e274), new Decimal(5e219), new Decimal(1e56), new Decimal(1e55), new Decimal(1e54), new Decimal(1e53), new Decimal(1e52), new Decimal(0), new Decimal(5e165), new Decimal(0), new Decimal(-1e55), new Decimal(-1e54), new Decimal(1e53), new Decimal(1e52), new Decimal(1e51), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e274)), false),
    new Building("Merapi View Elite Housing Estate (Level 1)", "An elite housing estate in the 9th kilometer of Kaliurang Street, Sleman Regency (Level 1)", new Decimal(0), new Decimal(5e279), new Decimal(5e223), new Decimal(1e57), new Decimal(1e56), new Decimal(1e55), new Decimal(1e54), new Decimal(1e53), new Decimal(0), new Decimal(5e168), new Decimal(0), new Decimal(-1e56), new Decimal(-1e55), new Decimal(1e54), new Decimal(1e53), new Decimal(1e52), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e279)), false),
    new Building("Bale Hinggil Housing Estate (Level 1)", "An elite housing estate near Gadjah Mada University at the 8th kilometer of Kaliurang Street, Ngaglik, Sleman Regency (Level 1).", new Decimal(0), new Decimal(5e284), new Decimal(5e227), new Decimal(1e58), new Decimal(1e57), new Decimal(1e56), new Decimal(1e55), new Decimal(1e54), new Decimal(0), new Decimal(5e171), new Decimal(0), new Decimal(-1e57), new Decimal(-1e56), new Decimal(1e55), new Decimal(1e54), new Decimal(1e53), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e284)), false),
    new Building("Demangan Elite Housing Complex (Level 1)", "An elite housing estate near Yogyakarta State University and Empire XXI (Level 1).", new Decimal(0), new Decimal(5e289), new Decimal(5e231), new Decimal(1e59), new Decimal(1e58), new Decimal(1e57), new Decimal(1e56), new Decimal(1e55), new Decimal(0), new Decimal(5e174), new Decimal(0), new Decimal(-1e58), new Decimal(-1e57), new Decimal(1e56), new Decimal(1e55), new Decimal(1e54), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), new Decimal(0), player.coins.gte(Decimal(5e289)), false),
    
    // ADD MORE BUILDINGS HERE
];

function Building(name, description, amount, coinCost, IDRCost, mCubeCost, kWhCost, workerCost, visitorCost, emptySpaceCost, specialCoinCost, coinProductionRate, IDRProductionRate, mCubeProductionRate, kWhProductionRate, workerProductionRate, visitorProductionRate, emptySpaceProductionRate, specialCoinProductionRate, actualCoinProductionRate, actualIDRProductionRate, actualmCubeProductionRate, actualkWhProductionRate, actualWorkerProductionRate, actualVisitorProductionRate, actualEmptySpaceProductionRate, actualSpecialCoinProductionRate, requirements, unlocked){
    this.name = name;
    this.description = description;
    this.amount = amount;
    this.coinCost = coinCost;
    this.IDRCost = IDRCost;
    this.mCubeCost = mCubeCost;
    this.kWhCost = kWhCost;
    this.workerCost = workerCost;
    this.visitorCost = visitorCost;
    this.emptySpaceCost = emptySpaceCost;
    this.specialCoinCost = specialCoinCost;
    this.coinProductionRate = coinProductionRate;
    this.IDRProductionRate = IDRProductionRate;
    this.mCubeProductionRate = mCubeProductionRate;
    this.kWhProductionRate = kWhProductionRate;
    this.workerProductionRate = workerProductionRate;
    this.visitorProductionRate = visitorProductionRate;
    this.emptySpaceProductionRate = emptySpaceProductionRate;
    this.specialCoinProductionRate = specialCoinProductionRate;
    this.actualCoinProductionRate = actualCoinProductionRate;
    this.actualIDRProductionRate = actualIDRProductionRate;
    this.actualmCubeProductionRate = actualmCubeProductionRate;
    this.actualkWhProductionRate = actualkWhProductionRate;
    this.actualWorkerProductionRate = actualWorkerProductionRate;
    this.actualVisitorProductionRate = actualVisitorProductionRate;
    this.actualEmptySpaceProductionRate = actualEmptySpaceProductionRate;
    this.actualSpecialCoinProductionRate = actualSpecialCoinProductionRate;
    this.requirements = requirements;
    this.unlocked = unlocked;
};

// MORE FUNCTIONS FOR BUILDING CLASS ARE TO BE ADDED
